_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "TwoStagePseudoLabGeneralizedRCNN"
  WEIGHTS: "output/model_0000999.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  PROPOSAL_GENERATOR:
    NAME: "PseudoLabRPN"
  RPN:
    POSITIVE_FRACTION: 0.25
    LOSS: "CrossEntropy"
  ROI_HEADS:
    NAME: "StandardROIHeadsPseudoLab"
    LOSS: "FocalLoss_BoundaryVar"
    NUM_CLASSES: 100
  ROI_BOX_HEAD:
    BBOX_REG_LOSS_TYPE: "nlloss"
    CLS_AGNOSTIC_BBOX_REG: True
SOLVER:
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  STEPS: (180000,)
  MAX_ITER: 180000
  IMG_PER_BATCH_LABEL: 60
  IMG_PER_BATCH_UNLABEL: 60
  BASE_LR: 0.01
  CHECKPOINT_PERIOD: 500
DATALOADER:
  SUP_PERCENT: 99.9
  RANDOM_DATA_SEED: 2
DATASETS:
  CROSS_DATASET: False
  TRAIN: ("1008_train",)
  TEST: ("1008_val",)
  TRAIN_LABEL: ("1008_val",)
SEMISUPNET:
  Trainer: "ubteacher_rcnn"
  BBOX_THRESHOLD: 0.7
  TEACHER_UPDATE_ITER: 1
  BURN_UP_STEP: 2000
  EMA_KEEP_RATE: 0.9996
  UNSUP_LOSS_WEIGHT: 4.0
  UNSUP_REG_LOSS_WEIGHT: 1.0
TEST:
  EVALUATOR: "COCOeval"
  VAL_LOSS: False
INPUT: # scale jittering (follow soft teacher)
  MIN_SIZE_TRAIN: (400, 1200)
  MIN_SIZE_TRAIN_SAMPLING: "range"
OUTPUT_DIR: "../../output/supervised"