_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "TwoStagePseudoLabGeneralizedRCNN"
  WEIGHTS: "output/model_supervised_pretrained_teacher_and_student.pkl"
  # output/supervised/model_0014999.pth
  # output/model_final_b275ba.pkl
  # output/model_supervised.pkl
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  PROPOSAL_GENERATOR:
    NAME: "PseudoLabRPN"
  RPN:
    POSITIVE_FRACTION: 0.25
    LOSS: "CrossEntropy"
  ROI_HEADS:
    NAME: "StandardROIHeadsPseudoLab"
    LOSS: "FocalLoss_BoundaryVar"
    NUM_CLASSES: 100
  ROI_BOX_HEAD:
    BBOX_REG_LOSS_TYPE: "nlloss"
    CLS_AGNOSTIC_BBOX_REG: True
SOLVER:
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  STEPS: (180000,)
  MAX_ITER: 180000
  IMG_PER_BATCH_LABEL: 18
  IMG_PER_BATCH_UNLABEL: 18
  BASE_LR: 0.004
  WARMUP_FACTOR: 0.0001
  WARMUP_ITERS: 1000
  CHECKPOINT_PERIOD: 1000
DATALOADER:
  SUP_PERCENT: 90.0
  RANDOM_DATA_SEED: 0
#  SAMPLER_TRAIN: "RepeatFactorTrainingSampler"
#  REPEAT_THRESHOLD: 0.202
DATASETS:
  CROSS_DATASET: True
  TRAIN: ("nyu_train",)
  TEST: ("nyu_val",)
  TRAIN_LABEL: ("nyu_train",)
  TRAIN_UNLABEL: ("nyu_unlabel",)
SEMISUPNET:
  Trainer: "ubteacher_rcnn"
  BBOX_THRESHOLD: 0.7
  TEACHER_UPDATE_ITER: 1
  BURN_UP_STEP: 2000
  EMA_KEEP_RATE: 0.9996
  UNSUP_LOSS_WEIGHT: 4.0
  UNSUP_REG_LOSS_WEIGHT: 1.0
TEST:
#  EVALUATOR: "COCOeval"
  VAL_LOSS: False
  EVAL_PERIOD: 1000
INPUT: # scale jittering (follow soft teacher)
  MIN_SIZE_TRAIN: (400, 1200)
  MIN_SIZE_TRAIN_SAMPLING: "range"
OUTPUT_DIR: "./output"